# docker compose up

# docker compose up -d
# docker compose stop
# docker compose rm
 
#  en gitignore agregar: .env.development

version: '3.8'

services:
  nestapp:
    build: ./
    ports:
      - "3001:3000"
    env_file:
      - .env.development
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env.development

volumes:
  pgdata: